{"error":{"code":101,"message":"Twitter auth is invalid for this user."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Twitter auth is invalid for this user.' }","timestamp":"2017-05-19T14:08:09.218Z"}
{"code":101,"message":"Twitter auth is invalid for this user.","level":"error","timestamp":"2017-05-19T14:08:09.222Z"}
{"error":{"name":"MongoError","message":"authentication fail","errors":[{"name":"aws-us-east-1-portal.22.dblayer.com:17650","err":{"name":"MongoError","message":"Authentication failed.","ok":0,"code":18,"errmsg":"Authentication failed."}},{"name":"aws-us-east-1-portal.21.dblayer.com:17650","err":{"name":"MongoError","message":"Authentication failed.","ok":0,"code":18,"errmsg":"Authentication failed."}}]},"level":"error","message":"Error generating response. { MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n  name: 'MongoError',\n  message: 'authentication fail',\n  errors: \n   [ { name: 'aws-us-east-1-portal.22.dblayer.com:17650',\n       err: [Object] },\n     { name: 'aws-us-east-1-portal.21.dblayer.com:17650',\n       err: [Object] } ] }","timestamp":"2017-05-19T17:42:24.357Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n  name: 'MongoError',\n  message: 'authentication fail',\n  errors: \n   [ { name: 'aws-us-east-1-portal.22.dblayer.com:17650',\n       err: [Object] },\n     { name: 'aws-us-east-1-portal.21.dblayer.com:17650',\n       err: [Object] } ] } MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","timestamp":"2017-05-19T17:42:24.359Z"}
{"error":{"name":"MongoError","message":"authentication fail","errors":[{"name":"aws-us-east-1-portal.21.dblayer.com:17650","err":{"name":"MongoError","message":"Authentication failed.","ok":0,"code":18,"errmsg":"Authentication failed."}}]},"level":"error","message":"Error generating response. { MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n  name: 'MongoError',\n  message: 'authentication fail',\n  errors: \n   [ { name: 'aws-us-east-1-portal.21.dblayer.com:17650',\n       err: [Object] } ] }","timestamp":"2017-05-19T17:43:30.483Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n  name: 'MongoError',\n  message: 'authentication fail',\n  errors: \n   [ { name: 'aws-us-east-1-portal.21.dblayer.com:17650',\n       err: [Object] } ] } MongoError: authentication fail\n    at Function.MongoError.create (/Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/error.js:31:11)\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/topologies/mongos.js:973:38\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:750:7\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:726:20\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/auth/scram.js:191:18\n    at /Users/davidokunibm/Afterparty/Server/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","timestamp":"2017-05-19T17:43:30.485Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2017-05-19T18:05:22.005Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2017-05-19T18:05:22.008Z"}
